[package]
name = "ghrm-git"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Shared Git operations for ghrm"
repository = "https://github.com/brege/ghrm"

[dependencies]
anyhow = "1"
gix = { workspace = true, features = [
  "blob-diff",
  "max-performance-safe",
  "revision",
  "sha1",
] }

[dev-dependencies]
gix = { workspace = true, features = ["tree-editor"] }
