import type { ReactElement } from 'react';
import { FaCode, FaRegCommentDots, FaRegNoteSticky } from 'react-icons/fa6';
import { FiCloudOff, FiEdit, FiMoon, FiSearch, FiSun } from 'react-icons/fi';
import {
  GoAlert,
  GoArrowUpRight,
  GoBook,
  GoCheck,
  GoChevronDown,
  GoChevronLeft,
  GoChevronRight,
  GoChevronUp,
  GoCode,
  GoColumns,
  GoCopy,
  GoDownload,
  GoFile,
  GoFileDirectoryFill,
  GoFilter,
  GoGitCommit,
  GoHome,
  GoLightBulb,
  GoListUnordered,
  GoLocation,
  GoPeople,
  GoRepoForked,
  GoScreenFull,
  GoSignOut,
  GoSortDesc,
  GoStop,
  GoSync,
  GoZoomIn,
  GoZoomOut,
} from 'react-icons/go';
import {
  SiBitbucket,
  SiCodeberg,
  SiGit,
  SiGithub,
  SiGitlab,
  SiSourcehut,
} from 'react-icons/si';
import {
  TbBrandSpeedtest,
  TbDatabase,
  TbEggCracked,
  TbFileDescription,
  TbFileSearch,
  TbFileSpreadsheet,
  TbFileZip,
  TbListSearch,
  TbRefresh,
  TbRepeat,
  TbScale,
  TbTable,
  TbTextWrap,
} from 'react-icons/tb';

type Icon = {
  id: string;
  icon: ReactElement;
};

export const icons: Icon[] = [
  { id: 'ghrm-icon-sun', icon: <FiSun /> },
  { id: 'ghrm-icon-moon', icon: <FiMoon /> },
  { id: 'ghrm-icon-search', icon: <FiSearch /> },
  { id: 'ghrm-icon-dir', icon: <GoFileDirectoryFill /> },
  { id: 'ghrm-icon-file', icon: <GoFile /> },
  { id: 'ghrm-icon-book', icon: <GoBook /> },
  { id: 'ghrm-icon-list', icon: <GoListUnordered /> },
  { id: 'ghrm-icon-search-path', icon: <TbListSearch /> },
  { id: 'ghrm-icon-search-content', icon: <TbFileSearch /> },
  { id: 'ghrm-icon-doc-framed', icon: <TbFileSpreadsheet /> },
  { id: 'ghrm-icon-doc-flat', icon: <TbFileDescription /> },
  { id: 'ghrm-icon-github', icon: <SiGithub /> },
  { id: 'ghrm-icon-fork', icon: <GoRepoForked /> },
  { id: 'ghrm-icon-bitbucket', icon: <SiBitbucket /> },
  { id: 'ghrm-icon-gitlab', icon: <SiGitlab /> },
  { id: 'ghrm-icon-codeberg', icon: <SiCodeberg /> },
  { id: 'ghrm-icon-sourcehut', icon: <SiSourcehut /> },
  { id: 'ghrm-icon-git', icon: <SiGit /> },
  { id: 'ghrm-icon-people', icon: <GoPeople /> },
  { id: 'ghrm-icon-scale', icon: <TbScale /> },
  { id: 'ghrm-icon-location', icon: <GoLocation /> },
  { id: 'ghrm-icon-created', icon: <TbEggCracked /> },
  { id: 'ghrm-icon-table', icon: <TbTable /> },
  { id: 'ghrm-icon-update', icon: <TbRefresh /> },
  { id: 'ghrm-icon-commit', icon: <GoGitCommit /> },
  { id: 'ghrm-icon-repeat', icon: <TbRepeat /> },
  { id: 'ghrm-icon-loc', icon: <GoCode /> },
  { id: 'ghrm-icon-data', icon: <TbDatabase /> },
  { id: 'ghrm-icon-code', icon: <FaCode /> },
  { id: 'ghrm-icon-download', icon: <GoDownload /> },
  { id: 'ghrm-icon-zst', icon: <TbBrandSpeedtest /> },
  { id: 'ghrm-icon-zip', icon: <TbFileZip /> },
  { id: 'ghrm-icon-wrap', icon: <TbTextWrap /> },
  { id: 'ghrm-icon-copy', icon: <GoCopy /> },
  { id: 'ghrm-icon-check', icon: <GoCheck /> },
  { id: 'ghrm-icon-fullscreen', icon: <GoScreenFull /> },
  { id: 'ghrm-icon-zoom-in', icon: <GoZoomIn /> },
  { id: 'ghrm-icon-zoom-out', icon: <GoZoomOut /> },
  { id: 'ghrm-icon-reset', icon: <GoSync /> },
  { id: 'ghrm-icon-filter', icon: <GoFilter /> },
  { id: 'ghrm-icon-sort-entity', icon: <GoSortDesc /> },
  { id: 'ghrm-icon-columns', icon: <GoColumns /> },
  { id: 'ghrm-icon-chevron-up', icon: <GoChevronUp /> },
  { id: 'ghrm-icon-chevron-down', icon: <GoChevronDown /> },
  { id: 'ghrm-icon-chevron-left', icon: <GoChevronLeft /> },
  { id: 'ghrm-icon-chevron-right', icon: <GoChevronRight /> },
  { id: 'ghrm-icon-home', icon: <GoHome /> },
  { id: 'ghrm-icon-note', icon: <FaRegNoteSticky /> },
  { id: 'ghrm-icon-edit', icon: <FiEdit /> },
  { id: 'ghrm-icon-tip', icon: <GoLightBulb /> },
  { id: 'ghrm-icon-important', icon: <FaRegCommentDots /> },
  { id: 'ghrm-icon-warning', icon: <GoAlert /> },
  { id: 'ghrm-icon-caution', icon: <GoStop /> },
  { id: 'ghrm-icon-external', icon: <GoArrowUpRight /> },
  { id: 'ghrm-icon-logout', icon: <GoSignOut /> },
  { id: 'ghrm-icon-cloud-offline', icon: <FiCloudOff /> },
];
