import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { defineConfig } from 'vite';

const __dirname = dirname(fileURLToPath(import.meta.url));
const srcRoot = resolve(__dirname, 'src');
const outRoot = resolve(__dirname, '../assets/js');
const banner = '/* @generated by ui vite build. Edit ui/src instead. */';

function generatedBanner() {
  return {
    name: 'ghrm-generated-banner',
    generateBundle(_, bundle) {
      for (const artifact of Object.values(bundle)) {
        if (artifact.type === 'chunk') {
          artifact.code = `${banner}\n${artifact.code}`;
        }
      }
    },
  };
}

const sharedModules = ['dom', 'prefs', 'vendor', 'status', 'live'];

function isSharedModule(id) {
  for (const name of sharedModules) {
    if (id.endsWith(`/${name}.js`) || id.endsWith(`/${name}.ts`)) {
      return true;
    }
  }
  return false;
}

export default defineConfig({
  plugins: [generatedBanner()],
  build: {
    outDir: outRoot,
    emptyOutDir: true,
    lib: {
      entry: {
        preview: resolve(srcRoot, 'preview.js'),
        main: resolve(srcRoot, 'main.js'),
        gist: resolve(srcRoot, 'gist.js'),
      },
      formats: ['es'],
      fileName: (_, name) => `${name}.js`,
    },
    rollupOptions: {
      output: {
        entryFileNames: '[name].js',
        chunkFileNames: 'chunks/[name].js',
        assetFileNames: '[name].[ext]',
        manualChunks: (id) => {
          if (id.includes('/adapters/')) {
            return 'adapters';
          }
          if (isSharedModule(id)) {
            return 'shared';
          }
          return undefined;
        },
      },
    },
    minify: false,
    sourcemap: false,
  },
});
